#!/bin/bash

runs=1000000
if [ $1 ]
then
    runs=$1
fi

lengths=( 150 250 300 )
algos=( "CPU" "SSE8" "SSE16" "AVX8" "AVX16" )
seed=$RANDOM

echo "Starting ${runs} runs with ${algos[@]}. Seed ${seed}."
echo -e "\nAlgo\tLen\tClock\tTime (s)"
echo -e "----\t---\t-------\t--------"

for algo in "${algos[@]}"
do
    for len in "${lengths[@]}"
    do
        ../src/salt --test --algorithm ${algo} --runs ${runs} --reads_min_len ${len} --reads_max_len ${len} --min_overlap 1 --seed ${seed} > output

        c=`grep "Clock time" output | cut -d":" -f2 | tr -d ' '`
        t=$(awk "BEGIN {printf \"%.6f\",${c}/1000000}")
        echo -e "${algo}\t${len}\t${c}\t${t}"
    done
    echo ""
done
rm -f output
